spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
#      use to auto-generate db ddl
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-target: 'create.sql'
#              drop-target: 'drop.sql'
#              create-source: metadata
#              drop-source: metadata


